config/routes.rb
Rails.application.routes.draw do
  get '/status/(:name)', to: 'dashboard#show', constraints: { name: /[^\/]+/ }, as: :status
  get '/status/(:name)/uncrawled', to: 'dashboard#uncrawled', constraints: { name: /[^\/]+/ }
  get '/status/(:name)/tester', to: 'dashboard#tester', constraints: { name: /[^\/]+/ }
  get '/status/(:name)/filters', to: 'dashboard#filters', constraints: { name: /[^\/]+/ }, as: :filters
  get '/status/(:name)/videos', to: 'dashboard#videos', constraints: { name: /[^\/]+/ }, as: :videos
  get '/status/(:name)/videos/unprocessed', to: 'dashboard#unprocessed_videos', constraints: { name: /[^\/]+/ }, as: :unprocessed_videos
  get '/status/(:name)/videos/error', to: 'dashboard#error_videos', constraints: { name: /[^\/]+/ }, as: :errored_videos
  get '/status/(:name)/videos/export/csv', to: 'dashboard#export_csv', constraints: { name: /[^\/]+/ }, as: :videos_export_csv

  resources :websites, only: [:index, :create] do
    member do
      get 'get_stats'
      get 'get_queue'

      post 'queue'
      patch 'update_page'
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  PAGE_QUEUE_LIMIT = 50

  before_action :find_website

  def show
    # Get the pages currently being crawled or recently crawled
    @queue = WebsiteService.pages_being_crawled(website: @website).limit(PAGE_QUEUE_LIMIT)
  end

  def uncrawled
    @pages = @website.pages.uncrawled.select(:id, :url).order(url: :asc)
  end

  def tester
    @pages = WebsiteService.pages_being_crawled(website: @website).select(:id, :status, :url)
  end

  def videos
    per_page = params[:per_page] || 250

    @videos = @website.videos
                      .where(status: [:processed, :error])
                      .includes(:page_for_delegation)
                      .order(created_at: :desc)
                      .paginate(page: params[:page], per_page: per_page)
  end

  def unprocessed_videos
    per_page = params[:per_page] || 250

    @videos = @website.videos
                      .pending
                      .includes(:page_for_delegation)
                      .paginate(page: params[:page], per_page: per_page)

    render :videos
  end

  def error_videos
    per_page = params[:per_page] || 250

    @videos = @website.videos
                      .error
                      .includes(:page_for_delegation)
                      .paginate(page: params[:page], per_page: per_page)

    render :videos
  end


  def filters
    @filters = @website.filters
  end

  def export_csv
    csv = VideoService.get_csv(website: @website)
    filename = "#{@website.name}_videos_export_#{Time.now.to_i}.csv"

    send_data csv, type: "text/csv; charset=utf-8; header=present", filename: filename
  end

  private

  def find_website
    @website = Website.find_by(name: params[:name])
  end
end

app/views/dashboard/filters.html.erb
<section class="filters">
  <div class="box">
    <%= @website.filters_regexp.to_s %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>type</th>
        <th>filter</th>
      </tr>
    </thead>
    <tbody>
    <% @filters.each do |f| %>
      <tr>
        <td><%= f.id %></td>
        <td><%= f.filter_type %></td>
        <td><%= f.filter %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/dashboard/show.html.erb
<h1><%= @website.url %></h1>

<section class="progress">
	<div class="progress-bar offline">
		<div class="progress" data-progress="0" data-stat="progress"></div>
	</div>
</section>

<section class="stats">
  <div class="row">
    <table class="table table--centered-text table--half">
      <thead>
        <tr>
          <th colspan="6">
            Pages
          </th>
        </tr>
        <tr>
          <th>%</th>
          <th>Crawled</th>
          <th>Total</th>
          <th>Rate</th>
          <th>Jobs</th>
          <th>Time Remaining</th>
        </tr>
      </thead>
      <tbody class="bordered">
        <tr>
          <td data-stat="percent">n/a</td>
          <td data-stat="crawled_pages">n/a</td>
          <td data-stat="total_pages">n/a</td>
          <td data-stat="pages_per_second">n/a</td>
          <td data-stat="jobs">n/a</td>
          <td data-stat="time_remaining">n/a</td>
        </tr>
      </tbody>
    </table>

    <table class="table table--centered-text table--half">
      <thead>
        <tr>
          <th colspan=4>
            Videos
          </th>
        </tr>
        <tr>
          <th>Processed</th>
          <th>Unprocessed</th>
          <th>Captioned</th>
          <th>Error</th>
        </tr>
      </thead>
      <tbody class="bordered">
        <tr>
          <td data-stat="num_videos">n/a</td>
          <td data-stat="num_videos_pending">n/a</td>
          <td data-stat="num_videos_captioned">n/a</td>
          <td data-stat="num_videos_error">n/a</td>
        </tr>
      </tbody>
    </table>
  </div>
</section>

<section class="page-queue">
	<table class="table table--full table--left-text">
		<thead>
			<tr>
				<th colspan="2" class="center">Current Page Queue</th>
			</tr>
			<tr>
        <th>
          Status
        </th>
				<th width="100%">
					URL
				</th>
			</tr>
		</thead>

		<tbody>
      <tr>
        <td colspan="2">
          Loading crawl queue...
        </td>
      </tr>
		</tbody>
  </table>
</section>

<script>
	document.addEventListener("DOMContentLoaded", function() {
		initialize();
	});

	function initialize() {
    update_stats();
    update_queue();
  }

  function update_crawl_status(status) {
    if (status == 'stopped') {
      $$('.progress-bar').classList.add('offline')
    } else {
      $$('.progress-bar').classList.remove('offline')
    }
  }

  function update_progress(progress) {
    var $bar = $$(".progress-bar .progress")
    $bar.dataset.progress = progress
    $bar.style.width = progress + "%";
  }

  function website_base_url() {
    return "/websites/<%= @website.id %>";
  }

  function render_queue(data) {
    let body = document.createElement("tbody");

    if (data.length == 0) {
      var oldQueueBody = $$(".page-queue table tbody");
      oldQueueBody.innerHTML = '<tr><td colspan="2">There are no pages being crawled or processed.</td></tr>'

      return
    }

    for (i in data) {
      let page = data[i];

      var tr = document.createElement("tr")

      var td = document.createElement("td")
      td.innerHTML = page.status
      td.classList.add("page")
      td.classList.add(page.status)
      tr.appendChild(td)

      var td = document.createElement("td")
      td.innerHTML = page.url
      td.classList.add("page")
      td.classList.add(page.status)
      tr.appendChild(td)
      body.appendChild(tr)
    }

    var queueTable = $$(".page-queue table");
    var oldQueueBody = $$(".page-queue table tbody");

    queueTable.replaceChild(body, oldQueueBody);
  }

  function update_queue() {
    fetch(website_base_url() + "/get_queue")
      .then(function(response) {
        return response.json()
      })
      .then(function(data) {
        render_queue(data)
      })
      .then(function() {
        setTimeout(update_queue, 2000)
      })
  }

	function update_stats() {
    fetch("/websites/<%= @website.id %>/get_stats")
      .then(function(response) {
        return response.json()
      })
      .then(function(data) {
        for (field in data) {
          let fieldSelector = "[data-stat=\"" + field + "\"]"
          let entity = $$(fieldSelector)

          if (entity) {
            entity.innerHTML = data[field]
          }

          if (field == 'num_videos') {
            let anchor = document.createElement("a")
            anchor.href = '<%= videos_path(name: @website.name) %>'
            anchor.innerHTML = data[field]
            entity.innerHTML = '';
            entity.appendChild(anchor)
          }

          if (field == 'crawl_status') {
            update_crawl_status(data[field])
          }

          // treat the progress bar differently
          if (field == 'percent') {
            update_progress(data[field])
          }
        }
      })
    .then(function() {
      setTimeout(update_stats, 5000)
    })
	}
</script>

app/views/dashboard/tester.html.erb
<section>
  <table class="table table--full">
    <thead>
      <tr>
        <th>ID</th>
        <th>Status</th>
        <th>URL</th>
      </tr>
    </thead>

    <tbody class="bordered">
      <% if @pages.any? %>
        <% @pages.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.status %></td>
          <td><%= p.url %></td>
        </tr>
        <% end %>
      <% else%>
        <tr>
          <td colspan="3">
            No uncrawled pages in the queue
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/dashboard/uncrawled.html.erb
<section>
  <table class="table table--full">
    <thead>
      <tr>
        <th>ID</th>
        <th>URL</th>
      </tr>
    </thead>

    <tbody class="bordered">
      <% if @pages.any? %>
        <% @pages.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.url %></td>
        </tr>
        <% end %>
      <% else%>
        <tr>
          <td colspan="2">
            No uncrawled pages in the queue
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/dashboard/videos.html.erb
<nav>
  <%= link_to '< Back to Dashboard', status_path(name: @website.name), class: "button" %>

  <button id="download-csv-button" class="button">Download CSV</button>
</nav>

<%= will_paginate @videos %>

<section class="videos">
  <table class="table table--full table--left-text">
    <thead>
      <tr>
        <th>id</th>
        <th>pid</th>
        <th>page url</th>
        <th>type</th>
        <th>views</th>
        <th>duration</th>
        <th>channel</th>
        <th>video source</th>
        <th>properties</th>
        <th>captioned?</th>
        <th>status</th>
        <th>updated</th>
      </tr>
    </thead>

    <tbody>
    <% @videos.each do |vid| %>
      <tr>
        <td><%= vid.id %></td>
        <td><%= vid.page_id %></td>
        <td><%= link_to(vid.page_url.truncate(100), vid.page_url) %></td>
        <td><%= vid.embed_type %></td>
        <td><%= vid.view_count %></td>
        <td><%= vid.duration %></td>
        <td><%= link_to_if(vid.channel_url.present?, vid.channel_name, vid.channel_url) %></td>
        <td><%= link_to(vid.url.truncate(100), vid.url, target: "_blank") %></td>
        <td><%= vid.properties %></td>
        <td><%= vid.captioned? ? "yes" : "" %></td>
        <td><%= vid.status %></td>
        <td class="nowrap"><%= vid.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

<%= will_paginate @videos %>

<iframe id="csv_download_region" aria-hidden="true" style="display: none;"></iframe>

<script>
	document.addEventListener("DOMContentLoaded", function() {
		initialize();
	});

	function initialize() {
    let btn = $$('#download-csv-button');

    if (btn) {
      btn.addEventListener('click', function(e) {
        e.preventDefault()
        btn.classList.add("generating")
        btn.innerHTML = "Generating..."
        btn.setAttribute("disabled", true)

        var url = '<%= videos_export_csv_path(@website.name) %>'

        $$('#csv_download_region').src = url

        setTimeout(function() {
          btn.classList.remove("generating")
          btn.removeAttribute("disabled");
          btn.innerHTML = 'Download CSV'
        }, 2500)
      });
    }
  }
</script>